# Generated by Django 3.1.12 on 2021-06-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattoo_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tattoo_description',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
